Repository SlamaFR/UGE-Bot, pull requests merged in 2021-09, with the labels that each got.

#50 Update gradle.yml
  .github/workflows/gradle.yml
Labels: Bug Fix

#49 Fix shusher message
  src/main/kotlin/io/slama/events/shusher.kt
Labels: Bug Fix

#48 Fixes an issue where the data folder was missing and moved calls and polls logs in dedicated folders
  .gitignore
  src/main/kotlin/io/slama/commands/call_command.kt
  src/main/kotlin/io/slama/commands/changen_command.kt
  src/main/kotlin/io/slama/commands/poll_command.kt
  src/main/kotlin/io/slama/core/config.kt
  src/main/kotlin/io/slama/events/shusher.kt
Labels: Enhancement, Bug Fix

#54 Handled Keval exceptions.
  .github/workflows/gradle.yml
  src/main/kotlin/io/slama/commands/keval_command.kt
Labels: Bug Fix

#55 Config rework, full reload, and missing folders
  src/main/kotlin/io/slama/commands/call_command.kt
  src/main/kotlin/io/slama/commands/poll_command.kt
  src/main/kotlin/io/slama/commands/table_command.kt
  src/main/kotlin/io/slama/core/commands.kt
  src/main/kotlin/io/slama/core/config.kt
  src/main/kotlin/io/slama/events/autoroles.kt
  src/main/kotlin/io/slama/events/shusher.kt
  src/main/kotlin/io/slama/main.kt
  src/main/kotlin/io/slama/utils/command_permissions.kt
Labels: Enhancement, Bug Fix

#56 Add GitHub action to automatically close issues when merging on versions branches
  .github/workflows/issues.yml
Labels: Enhancement

#57 Invalid token: user-friendly message
  src/main/kotlin/io/slama/main.kt
Labels: Enhancement

#59 Fix configuration reading file at each call.
  src/main/kotlin/io/slama/core/config.kt
Labels: Bug Fix

#60 Add more logging messages
  .github/workflows/issues.yml
  src/main/kotlin/io/slama/commands/call_command.kt
  src/main/kotlin/io/slama/commands/poll_command.kt
  src/main/kotlin/io/slama/core/config.kt
  src/main/kotlin/io/slama/main.kt
  src/main/resources/logback.xml
Labels: Enhancement

#61 Cleaned code style.
  src/main/kotlin/io/slama/commands/autorole_command.kt
  src/main/kotlin/io/slama/commands/call_command.kt
  src/main/kotlin/io/slama/commands/keval_command.kt
  src/main/kotlin/io/slama/commands/poll_command.kt
  src/main/kotlin/io/slama/commands/table_command.kt
  src/main/kotlin/io/slama/core/config.kt
  src/main/kotlin/io/slama/utils/command_dsl.kt
  src/main/kotlin/io/slama/utils/strings.kt
  src/main/kotlin/io/slama/utils/task_scheduler.kt
Labels: Enhancement

#62 2.0.1 Release
  .gitignore
  build.gradle.kts
  src/main/kotlin/io/slama/commands/autorole_command.kt
  src/main/kotlin/io/slama/commands/call_command.kt
  src/main/kotlin/io/slama/commands/changen_command.kt
  src/main/kotlin/io/slama/commands/keval_command.kt
  src/main/kotlin/io/slama/commands/poll_command.kt
  src/main/kotlin/io/slama/commands/table_command.kt
  src/main/kotlin/io/slama/core/commands.kt
  src/main/kotlin/io/slama/core/config.kt
  src/main/kotlin/io/slama/events/autoroles.kt
  src/main/kotlin/io/slama/events/shusher.kt
  src/main/kotlin/io/slama/main.kt
  src/main/kotlin/io/slama/utils/command_dsl.kt
  src/main/kotlin/io/slama/utils/command_permissions.kt
  src/main/kotlin/io/slama/utils/strings.kt
  src/main/kotlin/io/slama/utils/task_scheduler.kt
  src/main/resources/logback.xml
Labels: Release

#63 Fix autoroles guild conflit.
  build.gradle.kts
  src/main/kotlin/io/slama/events/autoroles.kt
Labels: Bug Fix

#64 Hotfix 2.0.2
  build.gradle.kts
  src/main/kotlin/io/slama/events/autoroles.kt
Labels: Release

#67 Mail announcement dispatcher
  build.gradle.kts
  src/main/kotlin/io/slama/core/config.kt
  src/main/kotlin/io/slama/main.kt
  src/main/kotlin/io/slama/managers/mail.kt
  src/main/kotlin/io/slama/utils/channels.kt
  src/main/kotlin/io/slama/utils/mails.kt
  src/main/kotlin/io/slama/utils/strings.kt
  src/test/kotlin/io/slama/utils/StringsTest.kt
Labels: Feature

#68 Added dependency to Ktlint
  build.gradle.kts
  src/main/kotlin/io/slama/commands/call_command.kt
  src/main/kotlin/io/slama/commands/changen_command.kt
  src/main/kotlin/io/slama/commands/keval_command.kt
  src/main/kotlin/io/slama/commands/poll_command.kt
  src/main/kotlin/io/slama/commands/table_command.kt
  src/main/kotlin/io/slama/core/commands.kt
  src/main/kotlin/io/slama/core/config.kt
  src/main/kotlin/io/slama/events/autoroles.kt
  src/main/kotlin/io/slama/managers/mail.kt
  src/main/kotlin/io/slama/utils/channels.kt
  src/main/kotlin/io/slama/utils/mails.kt
  src/test/kotlin/io/slama/utils/StringsTest.kt
Labels: Enhancement
