Repository SlamaFR/UGE-Bot, pull requests merged in 2022-04, with the labels that each got.

#96 Fixed StackOverflow bug when trying to backup the config even though there was none to be backed up
  src/main/kotlin/io/slama/core/config.kt
Labels: Bug Fix

#97 Add total targeted members of role
  src/main/kotlin/io/slama/commands/call_command.kt
Labels: Enhancement

#98 2.1.4 Release
  build.gradle.kts
  src/main/kotlin/io/slama/commands/call_command.kt
  src/main/kotlin/io/slama/core/config.kt
Labels: Release
