Repository SlamaFR/UGE-Bot, pull requests merged in 2022-01, with the labels that each got.

#83 Friendly error messages
  build.gradle.kts
  src/main/kotlin/io/slama/commands/call_command.kt
  src/main/kotlin/io/slama/commands/poll_command.kt
  src/main/kotlin/io/slama/events/autoroles.kt
  src/main/kotlin/io/slama/managers/mail.kt
  src/main/kotlin/io/slama/utils/replies.kt
Labels: Enhancement

#86 Fix broken AutoRole discrimination
  src/main/kotlin/io/slama/events/autoroles.kt
Labels: Bug Fix

#88 Fix broken temporary channels generators
  src/main/kotlin/io/slama/commands/changen_command.kt
Labels: Bug Fix

#87 Fixed config reloading with backups.
  src/main/kotlin/io/slama/core/config.kt
  src/main/kotlin/io/slama/events/shusher.kt
  src/main/kotlin/io/slama/main.kt
Labels: Bug Fix

#89 2.1.2 Release
  build.gradle.kts
  src/main/kotlin/io/slama/commands/call_command.kt
  src/main/kotlin/io/slama/commands/changen_command.kt
  src/main/kotlin/io/slama/commands/poll_command.kt
  src/main/kotlin/io/slama/core/commands.kt
  src/main/kotlin/io/slama/core/config.kt
  src/main/kotlin/io/slama/events/autoroles.kt
  src/main/kotlin/io/slama/events/shusher.kt
  src/main/kotlin/io/slama/main.kt
  src/main/kotlin/io/slama/managers/mail.kt
  src/main/kotlin/io/slama/utils/replies.kt
Labels: Release

#90 Fix broken presence fallback
  build.gradle.kts
  src/main/kotlin/io/slama/main.kt
Labels: Bug Fix

#91 2.1.3 Hotfix
  build.gradle.kts
  src/main/kotlin/io/slama/main.kt
Labels: Release
